service: testing-in-layers

frameworkVersion: '3'

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:service}-${self:custom.stage}

provider:
  architecture: arm64
  deploymentBucket:
    name: com.reference-architecture.deploys
    serverSideEncryption: AES256
  environment:
    TABLE_NAME: ${self:custom.tableName}
    NODE_ENV: ${self:custom.stage}
    FOO: 'foo'
    BAR: 'bar'
  logRetentionInDays: 7
  name: aws
  runtime: nodejs18.x
  stage: dev
  tags:
    lumigo:auto-trace: 'true'

functions:
  createProduct:
    handler: src/createProductHandler.default
    events:
      - http: 
          path: products
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt ProductsTable.Arn

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
  
  Outputs:
    TableName:
      Description: The name of the DDB table
      Value: !Ref ProductsTable


package:
  patterns:
    - config/**

plugins:
  - serverless-esbuild
  - serverless-iam-roles-per-function
  - serverless-deployment-bucket